//
//  DetailRouter.swift
//  Assignment
//
//  Created by Manshi Viramgama on 29/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Foundation

// MARK: DetailRouter
final class DetailRouter
{
    /// Builder
    /// - Parameter details: detail string
    /// - Returns: Viewcontroller
    func buildModule(details: String) -> UIViewController {
        let viewController = DetailViewController()
        let interactor = DetailInteractor()
        let presenter = DetailPresenter(interactor: interactor, router: self, details: details)
        viewController.presenter = presenter
        interactor.output = presenter
        return viewController
    }
}

// MARK: DetailRouting methods
extension DetailRouter: DetailRouting {}
